---

- name: create group for user
  group:
    name: '{{ odoo_user.username }}'
    gid: '{{ odoo_user.uid }}'
  when: odoo_user is defined

- name: create user
  user:
    name: '{{ odoo_user.username }}'
    group: '{{ odoo_user.username }}'
    groups: '{{ odoo_user.groups|join(",") }}'
    shell: '{{ odoo_user.shell }}'
    comment: '{{ odoo_user.name }}'
    uid: '{{ odoo_user.uid }}'
    home: '{{ odoo_user.home }}'
    createhome: '{{ odoo_user.createhomedir }}'
  when: odoo_user is defined

- name: create postgres odoo user
  become: true
  become_user: postgres
  postgresql_user:
    name: '{{ odoo_user.username }}'
    role_attr_flags: 'CREATEDB,NOCREATEROLE,NOSUPERUSER'
